language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install -g typescript
install:
  - npm install
script:
  - npm run lint
  - npm run test
  - npm run build
deploy:
  provider: npm
  email: "samuraitruong@hotmail.com"
  api_key: $NPM_AUTH_CODE
  skip_cleanup: true
  on:
    tags: false
    branch: develop