language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install -g typescript
install:
  - npm install
script: 
  - npm run build
  - npm run test
deploy:
  provider: npm
  email: "samuraitruong@hotmail.com"
  api_key: $NPM_AUTH_CODE
  skip_cleanup: true
  on:
    tags: true
    branch: master